services:
  - name: drive-mmovie
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://notpointbreak:Password246M@cluster0.gzxc2sc.mongodb.net/?retryWrites=true&w=majority
    autoDeploy: true
